site_name: AbacatePay
repo_url: https://github.com/AbacatePay/abacatepay-python-sdk
edit_uri: tree/main/docs/
site_description: O SDK oficial de Python para integram com a AbacatePay.
copyright: Copyright &copy; 2024 AbacatePay

nav:
  - Inicio: index.md
  - Tutoriais:
    - Como pegar minha chave de acesso: tutorials/getting_api_key.md
    - Implementando um fluxo de cobrança: tutorials/billing_flow.md
    - Gerenciando clientes: tutorials/managing_customers.md
    - Criando uma cobrança PIX: tutorials/creating_a_pix_payment.md
    - Criando um cupom de desconto: tutorials/applying_a_coupon.md
  - Como contribuir: contributing.md
  - Referencia da API (en):
    - Billings: api/billings.md
    - Coupons: api/coupons.md
    - Customers: api/customers.md
    - PIX QRCode: api/PIX_QRCode.md
    - Products: api/products.md

theme:
  name: material
  language: pt-BR
  favicon: assets/icons/favicon-32x32.png
  logo: assets/icons/logo.svg
  title: AbacatePay
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Alterar para tema claro
      primary: green
      accent: teal

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Alterar para tema escuro
      primary: green
      accent: teal

  icon:
    annotation: material/plus-circle
  features:
    - content.code.annotate
    - navigation.footer

plugins:
- macros
- search
- mkdocstrings:
    handlers:
      python:
        paths: [abacatepay]

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details

extra:
  org_name: AbacatePay
  help_email: ajuda@abacatepay.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AbacatePay

    - icon: fontawesome/brands/discord
      link: https://discord.gg/yB5yKzp4gF

    - icon: fontawesome/brands/twitter
      link: https://x.com/abacatepay

    - icon: fontawesome/brands/linkedin
      link: https://br.linkedin.com/company/abacatepay?trk=public_post_feed-actor-name

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/abacatepay