name: Run tests on Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt && \
          pip install pytest pytest-cov pytest-mock responses pytest-responses respx

      - name: Run tests
        run: |
          pytest
